### ISSUE TITLE
Script for local run

### ISSUE THREAD

**Issue by Glinttsd** [quantaosun/Dock-MD-FEP#1]
Hi quantao,
  Your script is really helpful. Can you provide a local version instead of colab version script? Since GPU resource on colab can not be freely available all the time. Many thanks!

**Comment by quantaosun** [comment]
Hi,
sorry for the late reply. I don't have one for the moment.
My recommendation is you could just move "stage 3" i.e., the Yank installation and after to your local machine, while keeping running jobs before that on Colab. I know there are also MD jobs before Yank, but they are very short and should be easy to finish. 
In case of no GPU is available on Colab to you. You can consider just connecting to its CPU resources and setting the MD simulation time shorter or even skipping the first MD for receptor optimisation. That should not influence the final Yank result   . After finishing stage 2, then you can download the output and run Yank locally.

**Comment by Glinttsd** [comment]
Hi quantao,
  Thanks for your advice, it is really helpful. One final question. What can I do to make it correct if the `forward` and `reverse` trace on the `Free Energy Trace for Equilibrium Stability` part does not converge? Is this divergence acceptable for getting a good results?

**Comment by quantaosun** [comment]
Increase the number of lambda windows will always help.

Good to generate the simulation health report (or the quality report) after having finished the simulation. 

To adjust other possible settings, check https://github.com/choderalab/yank/blob/master/Yank/reports/YANK_Health_Report_Example.ipynb.
